### ISSUE TITLE
Cannot import 2.0.0-rc2 into an ESM project

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/language-common#41]
If you try and import the new `@openfn/language-common` into a standard modern node module, you get the following error:

`Error: Dynamic require of "vm" is not supported`

This is coming out of JSONPath code (because JSONpath uses `vm` to evaluate strings).

It seems to be fine if you load into a cjs (require) module.

I'm pretty sure it happens because `vm` is an `external` in the language-common package build, so the runtime code is trying to `import()` it. I also note that it's being built as a cjs module, I wonder if building an esm bundle would help?

## Repro Steps

* Create a new folder
* `cd` into it and run `npm init -y`
* In `package.json`, add `"type": "module"`
* Run `npm install `@openfn/language-common@2.0.0-rc2`
* Create an `index.js` and add `import { fn } from '@openfn/language-common';`
* Run `node index.js`

**Comment by stuartc** [comment]
Confirmed on my side, cheers for the repro steps.

I'm going to try dropping in `jsonpath-plus` which appears to have an esm module, will probably sidestep this whole thing.

You're right we could side step this using cjs, either way I'm not keen on tricking/building a plugin for esbuild that throws out the dynamic require.

**Comment by stuartc** [comment]
@josephjclark please give `2.0.0-rc3` a go... think I fixed it..

**Comment by josephjclark** [comment]
There's a few issues tracking this on the esbuild side - this seems to be the main one: https://github.com/evanw/esbuild/issues/1921

Apparently it's blocking shopify and netlify, so nice to know I'm not alone I guess.

**Comment by josephjclark** [comment]
@stuartc That seems to work, thanks!

**Comment by stuartc** [comment]
If the fix I did works for us now, great - but we won't be out of the woods for this happening again. From a skim read of the issue above, you're right we're not alone at all - and there appears to be one or two plugins that may address dynamic require issues if we get them again.

I'm not particularly precious when it comes to dealing with libraries that were written without ESM consideration; in this instance we just needed an update (and I'm very sure a lot of adaptors have ancient deps). Anyway we will probably run into this again, first prize is updating or replacing a dep..
